//
// Created by Jérôme BUISINE on 17/07/2017.
//

#ifndef METAHEURISTICS_BINARYCOMBINATORYSOLUTION_H
#define METAHEURISTICS_BINARYCOMBINATORYSOLUTION_H


class BinaryCombinatorySolution {

};


#endif //METAHEURISTICS_BINARYCOMBINATORYSOLUTION_H
